// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommittedFilesColumns holds the columns for the "committed_files" table.
	CommittedFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "tit_commit_files", Type: field.TypeInt, Nullable: true},
	}
	// CommittedFilesTable holds the schema information for the "committed_files" table.
	CommittedFilesTable = &schema.Table{
		Name:       "committed_files",
		Columns:    CommittedFilesColumns,
		PrimaryKey: []*schema.Column{CommittedFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "committed_files_tit_commits_files",
				Columns:    []*schema.Column{CommittedFilesColumns[3]},
				RefColumns: []*schema.Column{TitCommitsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "extension", Type: field.TypeString},
		{Name: "contents", Type: field.TypeBytes},
		{Name: "number", Type: field.TypeInt},
		{Name: "description", Type: field.TypeString},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
	}
	// PagesColumns holds the columns for the "pages" table.
	PagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pathname", Type: field.TypeString},
		{Name: "number", Type: field.TypeInt},
		{Name: "title", Type: field.TypeString},
		{Name: "overview_sentence", Type: field.TypeString},
	}
	// PagesTable holds the schema information for the "pages" table.
	PagesTable = &schema.Table{
		Name:       "pages",
		Columns:    PagesColumns,
		PrimaryKey: []*schema.Column{PagesColumns[0]},
	}
	// RemotesColumns holds the columns for the "remotes" table.
	RemotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
	}
	// RemotesTable holds the schema information for the "remotes" table.
	RemotesTable = &schema.Table{
		Name:       "remotes",
		Columns:    RemotesColumns,
		PrimaryKey: []*schema.Column{RemotesColumns[0]},
	}
	// SectionsColumns holds the columns for the "sections" table.
	SectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slug", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Size: 50},
		{Name: "overview_sentence", Type: field.TypeString},
		{Name: "number", Type: field.TypeInt},
		{Name: "page_sections", Type: field.TypeInt, Nullable: true},
	}
	// SectionsTable holds the schema information for the "sections" table.
	SectionsTable = &schema.Table{
		Name:       "sections",
		Columns:    SectionsColumns,
		PrimaryKey: []*schema.Column{SectionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sections_pages_sections",
				Columns:    []*schema.Column{SectionsColumns[5]},
				RefColumns: []*schema.Column{PagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// StagedFilesColumns holds the columns for the "staged_files" table.
	StagedFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "content", Type: field.TypeString},
	}
	// StagedFilesTable holds the schema information for the "staged_files" table.
	StagedFilesTable = &schema.Table{
		Name:       "staged_files",
		Columns:    StagedFilesColumns,
		PrimaryKey: []*schema.Column{StagedFilesColumns[0]},
	}
	// TitCommitsColumns holds the columns for the "tit_commits" table.
	TitCommitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeInt},
		{Name: "message", Type: field.TypeString},
		{Name: "section_commits", Type: field.TypeInt, Nullable: true},
	}
	// TitCommitsTable holds the schema information for the "tit_commits" table.
	TitCommitsTable = &schema.Table{
		Name:       "tit_commits",
		Columns:    TitCommitsColumns,
		PrimaryKey: []*schema.Column{TitCommitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tit_commits_sections_commits",
				Columns:    []*schema.Column{TitCommitsColumns[3]},
				RefColumns: []*schema.Column{SectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TitCommitImagesColumns holds the columns for the "tit_commit_images" table.
	TitCommitImagesColumns = []*schema.Column{
		{Name: "tit_commit_id", Type: field.TypeInt},
		{Name: "image_id", Type: field.TypeUUID},
	}
	// TitCommitImagesTable holds the schema information for the "tit_commit_images" table.
	TitCommitImagesTable = &schema.Table{
		Name:       "tit_commit_images",
		Columns:    TitCommitImagesColumns,
		PrimaryKey: []*schema.Column{TitCommitImagesColumns[0], TitCommitImagesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tit_commit_images_tit_commit_id",
				Columns:    []*schema.Column{TitCommitImagesColumns[0]},
				RefColumns: []*schema.Column{TitCommitsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tit_commit_images_image_id",
				Columns:    []*schema.Column{TitCommitImagesColumns[1]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommittedFilesTable,
		ImagesTable,
		PagesTable,
		RemotesTable,
		SectionsTable,
		StagedFilesTable,
		TitCommitsTable,
		TitCommitImagesTable,
	}
)

func init() {
	CommittedFilesTable.ForeignKeys[0].RefTable = TitCommitsTable
	SectionsTable.ForeignKeys[0].RefTable = PagesTable
	TitCommitsTable.ForeignKeys[0].RefTable = SectionsTable
	TitCommitImagesTable.ForeignKeys[0].RefTable = TitCommitsTable
	TitCommitImagesTable.ForeignKeys[1].RefTable = ImagesTable
}
