// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GlobalConfigsColumns holds the columns for the "global_configs" table.
	GlobalConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString},
	}
	// GlobalConfigsTable holds the schema information for the "global_configs" table.
	GlobalConfigsTable = &schema.Table{
		Name:       "global_configs",
		Columns:    GlobalConfigsColumns,
		PrimaryKey: []*schema.Column{GlobalConfigsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GlobalConfigsTable,
	}
)

func init() {
}
