// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Creaft-JP/tit/db/local/ent/predicate"
	"github.com/Creaft-JP/tit/db/local/ent/remote"
)

// RemoteUpdate is the builder for updating Remote entities.
type RemoteUpdate struct {
	config
	hooks    []Hook
	mutation *RemoteMutation
}

// Where appends a list predicates to the RemoteUpdate builder.
func (ru *RemoteUpdate) Where(ps ...predicate.Remote) *RemoteUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetName sets the "name" field.
func (ru *RemoteUpdate) SetName(s string) *RemoteUpdate {
	ru.mutation.SetName(s)
	return ru
}

// SetURL sets the "url" field.
func (ru *RemoteUpdate) SetURL(s string) *RemoteUpdate {
	ru.mutation.SetURL(s)
	return ru
}

// Mutation returns the RemoteMutation object of the builder.
func (ru *RemoteUpdate) Mutation() *RemoteMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RemoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RemoteUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RemoteUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RemoteUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RemoteUpdate) check() error {
	if v, ok := ru.mutation.URL(); ok {
		if err := remote.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Remote.url": %w`, err)}
		}
	}
	return nil
}

func (ru *RemoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(remote.Table, remote.Columns, sqlgraph.NewFieldSpec(remote.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Name(); ok {
		_spec.SetField(remote.FieldName, field.TypeString, value)
	}
	if value, ok := ru.mutation.URL(); ok {
		_spec.SetField(remote.FieldURL, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RemoteUpdateOne is the builder for updating a single Remote entity.
type RemoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RemoteMutation
}

// SetName sets the "name" field.
func (ruo *RemoteUpdateOne) SetName(s string) *RemoteUpdateOne {
	ruo.mutation.SetName(s)
	return ruo
}

// SetURL sets the "url" field.
func (ruo *RemoteUpdateOne) SetURL(s string) *RemoteUpdateOne {
	ruo.mutation.SetURL(s)
	return ruo
}

// Mutation returns the RemoteMutation object of the builder.
func (ruo *RemoteUpdateOne) Mutation() *RemoteMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RemoteUpdate builder.
func (ruo *RemoteUpdateOne) Where(ps ...predicate.Remote) *RemoteUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RemoteUpdateOne) Select(field string, fields ...string) *RemoteUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Remote entity.
func (ruo *RemoteUpdateOne) Save(ctx context.Context) (*Remote, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RemoteUpdateOne) SaveX(ctx context.Context) *Remote {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RemoteUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RemoteUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RemoteUpdateOne) check() error {
	if v, ok := ruo.mutation.URL(); ok {
		if err := remote.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Remote.url": %w`, err)}
		}
	}
	return nil
}

func (ruo *RemoteUpdateOne) sqlSave(ctx context.Context) (_node *Remote, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(remote.Table, remote.Columns, sqlgraph.NewFieldSpec(remote.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Remote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, remote.FieldID)
		for _, f := range fields {
			if !remote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != remote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Name(); ok {
		_spec.SetField(remote.FieldName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.URL(); ok {
		_spec.SetField(remote.FieldURL, field.TypeString, value)
	}
	_node = &Remote{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
