// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Creaft-JP/tit/db/local/ent/committedfile"
	"github.com/Creaft-JP/tit/db/local/ent/image"
	"github.com/Creaft-JP/tit/db/local/ent/page"
	"github.com/Creaft-JP/tit/db/local/ent/remote"
	"github.com/Creaft-JP/tit/db/local/ent/schema"
	"github.com/Creaft-JP/tit/db/local/ent/section"
	"github.com/Creaft-JP/tit/db/local/ent/stagedfile"
	"github.com/Creaft-JP/tit/db/local/ent/titcommit"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	committedfileFields := schema.CommittedFile{}.Fields()
	_ = committedfileFields
	// committedfileDescPath is the schema descriptor for path field.
	committedfileDescPath := committedfileFields[0].Descriptor()
	// committedfile.PathValidator is a validator for the "path" field. It is called by the builders before save.
	committedfile.PathValidator = committedfileDescPath.Validators[0].(func(string) error)
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescExtension is the schema descriptor for extension field.
	imageDescExtension := imageFields[1].Descriptor()
	// image.ExtensionValidator is a validator for the "extension" field. It is called by the builders before save.
	image.ExtensionValidator = imageDescExtension.Validators[0].(func(string) error)
	// imageDescNumber is the schema descriptor for number field.
	imageDescNumber := imageFields[3].Descriptor()
	// image.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	image.NumberValidator = imageDescNumber.Validators[0].(func(int) error)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() uuid.UUID)
	pageFields := schema.Page{}.Fields()
	_ = pageFields
	// pageDescPathname is the schema descriptor for pathname field.
	pageDescPathname := pageFields[0].Descriptor()
	// page.PathnameValidator is a validator for the "pathname" field. It is called by the builders before save.
	page.PathnameValidator = pageDescPathname.Validators[0].(func(string) error)
	// pageDescNumber is the schema descriptor for number field.
	pageDescNumber := pageFields[1].Descriptor()
	// page.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	page.NumberValidator = pageDescNumber.Validators[0].(func(int) error)
	remoteFields := schema.Remote{}.Fields()
	_ = remoteFields
	// remoteDescURL is the schema descriptor for url field.
	remoteDescURL := remoteFields[1].Descriptor()
	// remote.URLValidator is a validator for the "url" field. It is called by the builders before save.
	remote.URLValidator = remoteDescURL.Validators[0].(func(string) error)
	sectionFields := schema.Section{}.Fields()
	_ = sectionFields
	// sectionDescSlug is the schema descriptor for slug field.
	sectionDescSlug := sectionFields[0].Descriptor()
	// section.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	section.SlugValidator = sectionDescSlug.Validators[0].(func(string) error)
	// sectionDescTitle is the schema descriptor for title field.
	sectionDescTitle := sectionFields[1].Descriptor()
	// section.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	section.TitleValidator = sectionDescTitle.Validators[0].(func(string) error)
	// sectionDescNumber is the schema descriptor for number field.
	sectionDescNumber := sectionFields[3].Descriptor()
	// section.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	section.NumberValidator = sectionDescNumber.Validators[0].(func(int) error)
	stagedfileFields := schema.StagedFile{}.Fields()
	_ = stagedfileFields
	// stagedfileDescPath is the schema descriptor for path field.
	stagedfileDescPath := stagedfileFields[0].Descriptor()
	// stagedfile.PathValidator is a validator for the "path" field. It is called by the builders before save.
	stagedfile.PathValidator = stagedfileDescPath.Validators[0].(func(string) error)
	titcommitFields := schema.TitCommit{}.Fields()
	_ = titcommitFields
	// titcommitDescNumber is the schema descriptor for number field.
	titcommitDescNumber := titcommitFields[0].Descriptor()
	// titcommit.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	titcommit.NumberValidator = titcommitDescNumber.Validators[0].(func(int) error)
	// titcommitDescMessage is the schema descriptor for message field.
	titcommitDescMessage := titcommitFields[1].Descriptor()
	// titcommit.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	titcommit.MessageValidator = titcommitDescMessage.Validators[0].(func(string) error)
}
