// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GlobalConfig is the predicate function for globalconfig builders.
type GlobalConfig func(*sql.Selector)

// LoginToken is the predicate function for logintoken builders.
type LoginToken func(*sql.Selector)
