// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CommittedFile is the predicate function for committedfile builders.
type CommittedFile func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// Remote is the predicate function for remote builders.
type Remote func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// StagedFile is the predicate function for stagedfile builders.
type StagedFile func(*sql.Selector)

// TitCommit is the predicate function for titcommit builders.
type TitCommit func(*sql.Selector)
