// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Remote is the predicate function for remote builders.
type Remote func(*sql.Selector)

// StagedFile is the predicate function for stagedfile builders.
type StagedFile func(*sql.Selector)
