// Code generated by ent, DO NOT EDIT.

package page

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Creaft-JP/tit/db/local/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Page {
	return predicate.Page(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Page {
	return predicate.Page(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Page {
	return predicate.Page(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Page {
	return predicate.Page(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Page {
	return predicate.Page(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Page {
	return predicate.Page(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Page {
	return predicate.Page(sql.FieldLTE(FieldID, id))
}

// Pathname applies equality check predicate on the "pathname" field. It's identical to PathnameEQ.
func Pathname(v string) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldPathname, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v int) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldNumber, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldTitle, v))
}

// OverviewSentence applies equality check predicate on the "overview_sentence" field. It's identical to OverviewSentenceEQ.
func OverviewSentence(v string) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldOverviewSentence, v))
}

// PathnameEQ applies the EQ predicate on the "pathname" field.
func PathnameEQ(v string) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldPathname, v))
}

// PathnameNEQ applies the NEQ predicate on the "pathname" field.
func PathnameNEQ(v string) predicate.Page {
	return predicate.Page(sql.FieldNEQ(FieldPathname, v))
}

// PathnameIn applies the In predicate on the "pathname" field.
func PathnameIn(vs ...string) predicate.Page {
	return predicate.Page(sql.FieldIn(FieldPathname, vs...))
}

// PathnameNotIn applies the NotIn predicate on the "pathname" field.
func PathnameNotIn(vs ...string) predicate.Page {
	return predicate.Page(sql.FieldNotIn(FieldPathname, vs...))
}

// PathnameGT applies the GT predicate on the "pathname" field.
func PathnameGT(v string) predicate.Page {
	return predicate.Page(sql.FieldGT(FieldPathname, v))
}

// PathnameGTE applies the GTE predicate on the "pathname" field.
func PathnameGTE(v string) predicate.Page {
	return predicate.Page(sql.FieldGTE(FieldPathname, v))
}

// PathnameLT applies the LT predicate on the "pathname" field.
func PathnameLT(v string) predicate.Page {
	return predicate.Page(sql.FieldLT(FieldPathname, v))
}

// PathnameLTE applies the LTE predicate on the "pathname" field.
func PathnameLTE(v string) predicate.Page {
	return predicate.Page(sql.FieldLTE(FieldPathname, v))
}

// PathnameContains applies the Contains predicate on the "pathname" field.
func PathnameContains(v string) predicate.Page {
	return predicate.Page(sql.FieldContains(FieldPathname, v))
}

// PathnameHasPrefix applies the HasPrefix predicate on the "pathname" field.
func PathnameHasPrefix(v string) predicate.Page {
	return predicate.Page(sql.FieldHasPrefix(FieldPathname, v))
}

// PathnameHasSuffix applies the HasSuffix predicate on the "pathname" field.
func PathnameHasSuffix(v string) predicate.Page {
	return predicate.Page(sql.FieldHasSuffix(FieldPathname, v))
}

// PathnameEqualFold applies the EqualFold predicate on the "pathname" field.
func PathnameEqualFold(v string) predicate.Page {
	return predicate.Page(sql.FieldEqualFold(FieldPathname, v))
}

// PathnameContainsFold applies the ContainsFold predicate on the "pathname" field.
func PathnameContainsFold(v string) predicate.Page {
	return predicate.Page(sql.FieldContainsFold(FieldPathname, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v int) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v int) predicate.Page {
	return predicate.Page(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...int) predicate.Page {
	return predicate.Page(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...int) predicate.Page {
	return predicate.Page(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v int) predicate.Page {
	return predicate.Page(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v int) predicate.Page {
	return predicate.Page(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v int) predicate.Page {
	return predicate.Page(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v int) predicate.Page {
	return predicate.Page(sql.FieldLTE(FieldNumber, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Page {
	return predicate.Page(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Page {
	return predicate.Page(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Page {
	return predicate.Page(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Page {
	return predicate.Page(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Page {
	return predicate.Page(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Page {
	return predicate.Page(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Page {
	return predicate.Page(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Page {
	return predicate.Page(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Page {
	return predicate.Page(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Page {
	return predicate.Page(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Page {
	return predicate.Page(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Page {
	return predicate.Page(sql.FieldContainsFold(FieldTitle, v))
}

// OverviewSentenceEQ applies the EQ predicate on the "overview_sentence" field.
func OverviewSentenceEQ(v string) predicate.Page {
	return predicate.Page(sql.FieldEQ(FieldOverviewSentence, v))
}

// OverviewSentenceNEQ applies the NEQ predicate on the "overview_sentence" field.
func OverviewSentenceNEQ(v string) predicate.Page {
	return predicate.Page(sql.FieldNEQ(FieldOverviewSentence, v))
}

// OverviewSentenceIn applies the In predicate on the "overview_sentence" field.
func OverviewSentenceIn(vs ...string) predicate.Page {
	return predicate.Page(sql.FieldIn(FieldOverviewSentence, vs...))
}

// OverviewSentenceNotIn applies the NotIn predicate on the "overview_sentence" field.
func OverviewSentenceNotIn(vs ...string) predicate.Page {
	return predicate.Page(sql.FieldNotIn(FieldOverviewSentence, vs...))
}

// OverviewSentenceGT applies the GT predicate on the "overview_sentence" field.
func OverviewSentenceGT(v string) predicate.Page {
	return predicate.Page(sql.FieldGT(FieldOverviewSentence, v))
}

// OverviewSentenceGTE applies the GTE predicate on the "overview_sentence" field.
func OverviewSentenceGTE(v string) predicate.Page {
	return predicate.Page(sql.FieldGTE(FieldOverviewSentence, v))
}

// OverviewSentenceLT applies the LT predicate on the "overview_sentence" field.
func OverviewSentenceLT(v string) predicate.Page {
	return predicate.Page(sql.FieldLT(FieldOverviewSentence, v))
}

// OverviewSentenceLTE applies the LTE predicate on the "overview_sentence" field.
func OverviewSentenceLTE(v string) predicate.Page {
	return predicate.Page(sql.FieldLTE(FieldOverviewSentence, v))
}

// OverviewSentenceContains applies the Contains predicate on the "overview_sentence" field.
func OverviewSentenceContains(v string) predicate.Page {
	return predicate.Page(sql.FieldContains(FieldOverviewSentence, v))
}

// OverviewSentenceHasPrefix applies the HasPrefix predicate on the "overview_sentence" field.
func OverviewSentenceHasPrefix(v string) predicate.Page {
	return predicate.Page(sql.FieldHasPrefix(FieldOverviewSentence, v))
}

// OverviewSentenceHasSuffix applies the HasSuffix predicate on the "overview_sentence" field.
func OverviewSentenceHasSuffix(v string) predicate.Page {
	return predicate.Page(sql.FieldHasSuffix(FieldOverviewSentence, v))
}

// OverviewSentenceEqualFold applies the EqualFold predicate on the "overview_sentence" field.
func OverviewSentenceEqualFold(v string) predicate.Page {
	return predicate.Page(sql.FieldEqualFold(FieldOverviewSentence, v))
}

// OverviewSentenceContainsFold applies the ContainsFold predicate on the "overview_sentence" field.
func OverviewSentenceContainsFold(v string) predicate.Page {
	return predicate.Page(sql.FieldContainsFold(FieldOverviewSentence, v))
}

// HasSections applies the HasEdge predicate on the "sections" edge.
func HasSections() predicate.Page {
	return predicate.Page(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SectionsTable, SectionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSectionsWith applies the HasEdge predicate on the "sections" edge with a given conditions (other predicates).
func HasSectionsWith(preds ...predicate.Section) predicate.Page {
	return predicate.Page(func(s *sql.Selector) {
		step := newSectionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Page) predicate.Page {
	return predicate.Page(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Page) predicate.Page {
	return predicate.Page(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Page) predicate.Page {
	return predicate.Page(sql.NotPredicates(p))
}
