// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Creaft-JP/tit/db/global/ent/globalconfig"
)

// GlobalConfig is the model entity for the GlobalConfig schema.
type GlobalConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value        string `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GlobalConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case globalconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case globalconfig.FieldKey, globalconfig.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GlobalConfig fields.
func (gc *GlobalConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case globalconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gc.ID = int(value.Int64)
		case globalconfig.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				gc.Key = value.String
			}
		case globalconfig.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				gc.Value = value.String
			}
		default:
			gc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the GlobalConfig.
// This includes values selected through modifiers, order, etc.
func (gc *GlobalConfig) GetValue(name string) (ent.Value, error) {
	return gc.selectValues.Get(name)
}

// Update returns a builder for updating this GlobalConfig.
// Note that you need to call GlobalConfig.Unwrap() before calling this method if this GlobalConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (gc *GlobalConfig) Update() *GlobalConfigUpdateOne {
	return NewGlobalConfigClient(gc.config).UpdateOne(gc)
}

// Unwrap unwraps the GlobalConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gc *GlobalConfig) Unwrap() *GlobalConfig {
	_tx, ok := gc.config.driver.(*txDriver)
	if !ok {
		panic("ent: GlobalConfig is not a transactional entity")
	}
	gc.config.driver = _tx.drv
	return gc
}

// String implements the fmt.Stringer.
func (gc *GlobalConfig) String() string {
	var builder strings.Builder
	builder.WriteString("GlobalConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gc.ID))
	builder.WriteString("key=")
	builder.WriteString(gc.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(gc.Value)
	builder.WriteByte(')')
	return builder.String()
}

// GlobalConfigs is a parsable slice of GlobalConfig.
type GlobalConfigs []*GlobalConfig
