// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Creaft-JP/tit/db/global/ent/globalconfig"
	"github.com/Creaft-JP/tit/db/global/ent/predicate"
)

// GlobalConfigQuery is the builder for querying GlobalConfig entities.
type GlobalConfigQuery struct {
	config
	ctx        *QueryContext
	order      []globalconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.GlobalConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GlobalConfigQuery builder.
func (gcq *GlobalConfigQuery) Where(ps ...predicate.GlobalConfig) *GlobalConfigQuery {
	gcq.predicates = append(gcq.predicates, ps...)
	return gcq
}

// Limit the number of records to be returned by this query.
func (gcq *GlobalConfigQuery) Limit(limit int) *GlobalConfigQuery {
	gcq.ctx.Limit = &limit
	return gcq
}

// Offset to start from.
func (gcq *GlobalConfigQuery) Offset(offset int) *GlobalConfigQuery {
	gcq.ctx.Offset = &offset
	return gcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gcq *GlobalConfigQuery) Unique(unique bool) *GlobalConfigQuery {
	gcq.ctx.Unique = &unique
	return gcq
}

// Order specifies how the records should be ordered.
func (gcq *GlobalConfigQuery) Order(o ...globalconfig.OrderOption) *GlobalConfigQuery {
	gcq.order = append(gcq.order, o...)
	return gcq
}

// First returns the first GlobalConfig entity from the query.
// Returns a *NotFoundError when no GlobalConfig was found.
func (gcq *GlobalConfigQuery) First(ctx context.Context) (*GlobalConfig, error) {
	nodes, err := gcq.Limit(1).All(setContextOp(ctx, gcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{globalconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gcq *GlobalConfigQuery) FirstX(ctx context.Context) *GlobalConfig {
	node, err := gcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GlobalConfig ID from the query.
// Returns a *NotFoundError when no GlobalConfig ID was found.
func (gcq *GlobalConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcq.Limit(1).IDs(setContextOp(ctx, gcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{globalconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gcq *GlobalConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := gcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GlobalConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GlobalConfig entity is found.
// Returns a *NotFoundError when no GlobalConfig entities are found.
func (gcq *GlobalConfigQuery) Only(ctx context.Context) (*GlobalConfig, error) {
	nodes, err := gcq.Limit(2).All(setContextOp(ctx, gcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{globalconfig.Label}
	default:
		return nil, &NotSingularError{globalconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gcq *GlobalConfigQuery) OnlyX(ctx context.Context) *GlobalConfig {
	node, err := gcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GlobalConfig ID in the query.
// Returns a *NotSingularError when more than one GlobalConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (gcq *GlobalConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcq.Limit(2).IDs(setContextOp(ctx, gcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{globalconfig.Label}
	default:
		err = &NotSingularError{globalconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gcq *GlobalConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := gcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GlobalConfigs.
func (gcq *GlobalConfigQuery) All(ctx context.Context) ([]*GlobalConfig, error) {
	ctx = setContextOp(ctx, gcq.ctx, "All")
	if err := gcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GlobalConfig, *GlobalConfigQuery]()
	return withInterceptors[[]*GlobalConfig](ctx, gcq, qr, gcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gcq *GlobalConfigQuery) AllX(ctx context.Context) []*GlobalConfig {
	nodes, err := gcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GlobalConfig IDs.
func (gcq *GlobalConfigQuery) IDs(ctx context.Context) (ids []int, err error) {
	if gcq.ctx.Unique == nil && gcq.path != nil {
		gcq.Unique(true)
	}
	ctx = setContextOp(ctx, gcq.ctx, "IDs")
	if err = gcq.Select(globalconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gcq *GlobalConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := gcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gcq *GlobalConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gcq.ctx, "Count")
	if err := gcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gcq, querierCount[*GlobalConfigQuery](), gcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gcq *GlobalConfigQuery) CountX(ctx context.Context) int {
	count, err := gcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gcq *GlobalConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gcq.ctx, "Exist")
	switch _, err := gcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gcq *GlobalConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := gcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GlobalConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gcq *GlobalConfigQuery) Clone() *GlobalConfigQuery {
	if gcq == nil {
		return nil
	}
	return &GlobalConfigQuery{
		config:     gcq.config,
		ctx:        gcq.ctx.Clone(),
		order:      append([]globalconfig.OrderOption{}, gcq.order...),
		inters:     append([]Interceptor{}, gcq.inters...),
		predicates: append([]predicate.GlobalConfig{}, gcq.predicates...),
		// clone intermediate query.
		sql:  gcq.sql.Clone(),
		path: gcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GlobalConfig.Query().
//		GroupBy(globalconfig.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gcq *GlobalConfigQuery) GroupBy(field string, fields ...string) *GlobalConfigGroupBy {
	gcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GlobalConfigGroupBy{build: gcq}
	grbuild.flds = &gcq.ctx.Fields
	grbuild.label = globalconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.GlobalConfig.Query().
//		Select(globalconfig.FieldKey).
//		Scan(ctx, &v)
func (gcq *GlobalConfigQuery) Select(fields ...string) *GlobalConfigSelect {
	gcq.ctx.Fields = append(gcq.ctx.Fields, fields...)
	sbuild := &GlobalConfigSelect{GlobalConfigQuery: gcq}
	sbuild.label = globalconfig.Label
	sbuild.flds, sbuild.scan = &gcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GlobalConfigSelect configured with the given aggregations.
func (gcq *GlobalConfigQuery) Aggregate(fns ...AggregateFunc) *GlobalConfigSelect {
	return gcq.Select().Aggregate(fns...)
}

func (gcq *GlobalConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gcq); err != nil {
				return err
			}
		}
	}
	for _, f := range gcq.ctx.Fields {
		if !globalconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gcq.path != nil {
		prev, err := gcq.path(ctx)
		if err != nil {
			return err
		}
		gcq.sql = prev
	}
	return nil
}

func (gcq *GlobalConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GlobalConfig, error) {
	var (
		nodes = []*GlobalConfig{}
		_spec = gcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GlobalConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GlobalConfig{config: gcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gcq *GlobalConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gcq.querySpec()
	_spec.Node.Columns = gcq.ctx.Fields
	if len(gcq.ctx.Fields) > 0 {
		_spec.Unique = gcq.ctx.Unique != nil && *gcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gcq.driver, _spec)
}

func (gcq *GlobalConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(globalconfig.Table, globalconfig.Columns, sqlgraph.NewFieldSpec(globalconfig.FieldID, field.TypeInt))
	_spec.From = gcq.sql
	if unique := gcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gcq.path != nil {
		_spec.Unique = true
	}
	if fields := gcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, globalconfig.FieldID)
		for i := range fields {
			if fields[i] != globalconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gcq *GlobalConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gcq.driver.Dialect())
	t1 := builder.Table(globalconfig.Table)
	columns := gcq.ctx.Fields
	if len(columns) == 0 {
		columns = globalconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gcq.sql != nil {
		selector = gcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gcq.ctx.Unique != nil && *gcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gcq.predicates {
		p(selector)
	}
	for _, p := range gcq.order {
		p(selector)
	}
	if offset := gcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GlobalConfigGroupBy is the group-by builder for GlobalConfig entities.
type GlobalConfigGroupBy struct {
	selector
	build *GlobalConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gcgb *GlobalConfigGroupBy) Aggregate(fns ...AggregateFunc) *GlobalConfigGroupBy {
	gcgb.fns = append(gcgb.fns, fns...)
	return gcgb
}

// Scan applies the selector query and scans the result into the given value.
func (gcgb *GlobalConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcgb.build.ctx, "GroupBy")
	if err := gcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GlobalConfigQuery, *GlobalConfigGroupBy](ctx, gcgb.build, gcgb, gcgb.build.inters, v)
}

func (gcgb *GlobalConfigGroupBy) sqlScan(ctx context.Context, root *GlobalConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gcgb.fns))
	for _, fn := range gcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gcgb.flds)+len(gcgb.fns))
		for _, f := range *gcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GlobalConfigSelect is the builder for selecting fields of GlobalConfig entities.
type GlobalConfigSelect struct {
	*GlobalConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gcs *GlobalConfigSelect) Aggregate(fns ...AggregateFunc) *GlobalConfigSelect {
	gcs.fns = append(gcs.fns, fns...)
	return gcs
}

// Scan applies the selector query and scans the result into the given value.
func (gcs *GlobalConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcs.ctx, "Select")
	if err := gcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GlobalConfigQuery, *GlobalConfigSelect](ctx, gcs.GlobalConfigQuery, gcs, gcs.inters, v)
}

func (gcs *GlobalConfigSelect) sqlScan(ctx context.Context, root *GlobalConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gcs.fns))
	for _, fn := range gcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
