// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Creaft-JP/tit/db/global/ent/globalconfig"
	"github.com/Creaft-JP/tit/db/global/ent/logintoken"
	"github.com/Creaft-JP/tit/db/global/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	globalconfigFields := schema.GlobalConfig{}.Fields()
	_ = globalconfigFields
	// globalconfigDescKey is the schema descriptor for key field.
	globalconfigDescKey := globalconfigFields[0].Descriptor()
	// globalconfig.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	globalconfig.KeyValidator = globalconfigDescKey.Validators[0].(func(string) error)
	// globalconfigDescValue is the schema descriptor for value field.
	globalconfigDescValue := globalconfigFields[1].Descriptor()
	// globalconfig.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	globalconfig.ValueValidator = globalconfigDescValue.Validators[0].(func(string) error)
	logintokenFields := schema.LoginToken{}.Fields()
	_ = logintokenFields
	// logintokenDescSignInUserSlug is the schema descriptor for sign_in_user_slug field.
	logintokenDescSignInUserSlug := logintokenFields[0].Descriptor()
	// logintoken.SignInUserSlugValidator is a validator for the "sign_in_user_slug" field. It is called by the builders before save.
	logintoken.SignInUserSlugValidator = logintokenDescSignInUserSlug.Validators[0].(func(string) error)
	// logintokenDescCliLoginToken is the schema descriptor for cli_login_token field.
	logintokenDescCliLoginToken := logintokenFields[1].Descriptor()
	// logintoken.CliLoginTokenValidator is a validator for the "cli_login_token" field. It is called by the builders before save.
	logintoken.CliLoginTokenValidator = logintokenDescCliLoginToken.Validators[0].(func(string) error)
}
