on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    runs-on: ubuntu-latest
    container: goreleaser/goreleaser-cross
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: chown -R root:root ./
      - run: go mod tidy
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAKECHAN_ACCESS_TOKEN: ${{ secrets.TAKECHAN_ACCESS_TOKEN }}