on:
  pull_request:
    branches:
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: sudo apt-get install -y gcc-aarch64-linux-gnu
      - run: go test ./... -v
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot