on:
  pull_request:
    branches:
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - run: go test ./... -v
      - run: go build -v -x
        env:
          GOARCH: arm
          GOOS: linux
          CGO_ENABLED: 1
          CC_FOR_linux_arm: aarch64-linux-gnu-gcc
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot