on:
  pull_request:
    branches:
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: install C cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - run: go build
        env:
          GOARCH: arm64
          GOOS: linux
          CGO_ENABLED: 1
          CC: gcc
      - run: go test ./... -v
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot
        env:
          CC_FOR_linux_arm64: aarch64-linux-gnu-gcc