on:
  pull_request:
    branches:
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    container: goreleaser/goreleaser-cross
    steps:
      - uses: actions/checkout@v3
      - run: sudo chown -R ${USER} ./
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: go test ./... -v
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot