on:
  pull_request:
    branches:
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    container: goreleaser/goreleaser-cross
    steps:
      - uses: actions/checkout@v3
      - run: chown -R root:root ./
      - run: go mod tidy
      - run: go test ./... -v
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --snapshot